"""Local pytest execution and transparent, non-AI feedback."""
from __future__ import annotations

from collections import Counter
from pathlib import Path
import ast
import hashlib
import json
import os
import re
import shutil
import signal
import subprocess
import sys
import tempfile
import time

ROOT = Path(__file__).resolve().parents[1]
CATALOG = json.loads((ROOT / 'app/catalog.json').read_text(encoding='utf-8'))
CATALOG['flows'] = json.loads((ROOT / 'app/flows.json').read_text(encoding='utf-8'))
_guides = json.loads((ROOT / 'app/lesson_guides.json').read_text(encoding='utf-8'))
for _lesson in CATALOG['lessons']:
    _lesson['orientation'] = _guides[_lesson['id']]
LESSONS = {lesson['id']: lesson for lesson in CATALOG['lessons']}
MAX_CODE = 128_000


def fingerprint(text: str) -> str:
    return hashlib.sha256(text.encode('utf-8')).hexdigest()


def kill_process_tree(process: subprocess.Popen) -> None:
    if os.name == 'posix':
        try:
            os.killpg(process.pid, signal.SIGKILL)
        except ProcessLookupError:
            pass
    elif process.poll() is None:
        try:
            subprocess.run(['taskkill', '/F', '/T', '/PID', str(process.pid)],
                           stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, timeout=3)
        except (OSError, subprocess.TimeoutExpired):
            process.kill()


def coaching_tip(nodeid: str, detail: str, lesson: dict) -> str:
    """Test-specific coaching, not a diagnosis generated by a model."""
    if 'NotImplementedError' in detail:
        return 'The execution reached a starter stub. Implement the target function instead of changing the assertion.'
    rules = [
        (('repetition', 'once_per_query', 'both-fields'), 'Each distinct term earns title and body points independently. Repetition earns no additional points.'),
        (('whole_token', 'whole-tokens'), 'Use the supplied tokenizer. Substring matches such as notice inside notices are excluded by this contract.'),
        (('other-public', 'other-matching', 'tenant', 'permission', 'no_leak'), 'Recheck the tenant gate first, then the within-tenant permission rule. Public is not cross-tenant public.'),
        (('ties_sorted', 'sorts_identity', 'top_two'), 'Use an explicit deterministic tie-break. Reversing the entire sort may reverse both criteria.'),
        (('filter_before_limit', 'limits_after'), 'Build eligible matches before ranking and limiting. A denied result must not consume a result slot.'),
        (('validate', 'invalid_limit', 'invalid_event'), 'Validate before short-circuiting empty or stale input. Invalid arguments must not be silently accepted.'),
        (('empty_filter', 'category_or', 'stage3', 'no_filter'), 'Distinguish None from an empty filter. Use OR overlap; do not normalize case unless the contract says to.'),
        (('highest_not_last',), 'Arrival order is not source-version order. Keep the greatest version per composite identity.'),
        (('equal_version',), 'In the warm-up only, equal versions use the last incoming payload. Do not substitute the ingestion conflict rule.'),
        (('source_version', 'tombstone', 'resurrect', 'restore_deleted'), 'A tombstone stores a revision. Ignore older events; do not discard deletion history or replace source versions with a local counter.'),
        (('conflict',), 'Compare same-revision payloads before any mutation. Different payloads at the same revision are conflicts.'),
        (('duplicate', 'same_chunk'), 'Check this exercise’s identity and duplicate policy precisely. Seen items and selected items may be different sets.'),
        (('skip_large', 'size', 'budget'), 'Skip an oversized whole chunk and continue. Only selected chunks consume budget, but seen-identity rules still apply.'),
        (('cap_per_document',), 'Count selected chunks per document, not per chunk ID. A skipped candidate should not consume a selection slot.'),
        (('generator', 'one_shot', 'unchanged'), 'Consume the supplied iterable once. Do not require indexing or mutate the original collection.'),
        (('cancel',), 'Caller cancellation must unwind the operation. Cancel and await owned children instead of converting cancellation to an ordinary failure.'),
        (('queue_wait',), 'Start a source timeout only after its concurrency slot is acquired. Queue time must not spend the source-call budget.'),
        (('concurrent', 'parallel', 'concurrency'), 'Use concurrently scheduled work with a bound on active calls. Serial awaits or blocking sleep can prevent overlap.'),
        (('partial',), 'Distinguish a failed dependency from a successful empty result. Streaming output also changes whether fallback is safe.'),
        (('split', 'buffered', 'unneeded', 'trailing', 'crlf'), 'Preserve the incomplete suffix and emit complete buffered lines before requesting more input.'),
        (('schema', 'malformed', 'invalid_json'), 'Validate the exact event keys and value types. Preserve already emitted events before reporting a later malformed line.'),
        (('mutable_default',), 'Default objects are shared across calls. Use None and create the fresh list inside the function.'),
    ]
    for keys, tip in rules:
        if any(key in nodeid.lower() for key in keys):
            return tip
    if 'TypeError' in detail:
        return 'Check the public signature and return type. For streaming tasks, callers need an async iterator/generator, not an un-awaited coroutine.'
    return 'Read the assertion’s expected and observed values below. Reproduce this case by hand, then check the relevant acceptance rule.'


def run_code(lesson: dict, code: str, *, timeout_s: float = 20.0) -> dict:
    if lesson['kind'] != 'code':
        raise ValueError('This activity is not a coding exercise.')
    if not isinstance(code, str) or len(code.encode('utf-8')) > MAX_CODE:
        raise ValueError('Code must be text under 128 KB.')
    started = time.monotonic()
    result = {'lesson_id': lesson['id'], 'code_hash': fingerprint(code), 'submitted_text': code,
              'python': sys.version.split()[0], 'records': [], 'collection_errors': [],
              'passed': 0, 'failed': 0, 'skipped': 0, 'collected': 0,
              'success': False, 'timed_out': False, 'output_limit': False,
              'tips': [], 'output': '', 'exit_code': None}
    try:
        ast.parse(code, filename=lesson['file'])
    except SyntaxError as error:
        result.update(elapsed=round(time.monotonic()-started, 3),
                      collection_errors=[f'{type(error).__name__}: {error.msg}\n'
                                         f'{lesson["file"]}, line {error.lineno}\n'
                                         f'{error.text or ""}'],
                      tips=['Python could not parse your file, so no acceptance tests ran. Fix the indicated line/indentation first.'])
        return result

    with tempfile.TemporaryDirectory(prefix='judgelab-') as directory:
        work = Path(directory)
        shutil.copytree(ROOT / 'packs' / lesson['pack'], work, dirs_exist_ok=True,
                        ignore=shutil.ignore_patterns('__pycache__', '*.pyc', '.pytest_cache', '.venv'))
        (work / lesson['file']).write_text(code, encoding='utf-8')
        shutil.copyfile(ROOT / 'app/pytest_runner.py', work / '_lab_runner.py')
        (work / '.lab-pytest.ini').write_text(
            '[pytest]\nasyncio_mode = auto\nasyncio_default_fixture_loop_scope = function\n', encoding='utf-8')
        command = [sys.executable, '-I', str(work / '_lab_runner.py'), *lesson['tests']]
        if lesson.get('selection'):
            command += ['-k', lesson['selection']]
        environment = {k: v for k, v in os.environ.items()
                       if k in ('PATH', 'SYSTEMROOT', 'WINDIR', 'COMSPEC', 'PATHEXT', 'TEMP', 'TMP', 'LANG', 'LC_ALL')}
        environment.update(HOME=str(work), USERPROFILE=str(work),
                           PYTEST_DISABLE_PLUGIN_AUTOLOAD='1', PYTHONDONTWRITEBYTECODE='1',
                           PYTHONIOENCODING='utf-8')
        log = work / '.lab-output.txt'
        with log.open('wb') as output:
            options = {'start_new_session': True} if os.name == 'posix' else {}
            process = subprocess.Popen(command, cwd=work, env=environment,
                                       stdin=subprocess.DEVNULL, stdout=output, stderr=subprocess.STDOUT,
                                       **options)
            while process.poll() is None:
                if time.monotonic()-started > timeout_s:
                    result['timed_out'] = True
                    kill_process_tree(process)
                    break
                if log.stat().st_size > 256_000:
                    result['output_limit'] = True
                    kill_process_tree(process)
                    break
                time.sleep(0.035)
            try:
                process.wait(timeout=3)
            except subprocess.TimeoutExpired:
                process.kill()
                process.wait()
            # Also clean up descendants left after an ordinary parent exit on POSIX.
            if os.name == 'posix':
                kill_process_tree(process)
        result['exit_code'] = process.returncode
        result['output'] = log.read_bytes()[-64_000:].decode('utf-8', 'replace').replace(str(work), '<workspace>')
        report_path = work / '.lab-report.json'
        if report_path.exists():
            try:
                report = json.loads(report_path.read_text(encoding='utf-8'))
                result['collected'] = report.get('collected', 0)
                result['collection_errors'] = report.get('collection_errors', [])
                result['records'] = list(report.get('records', {}).values())
            except (ValueError, OSError):
                result['collection_errors'].append('The test process did not produce a readable result report.')
        else:
            result['collection_errors'].append('The test process ended before producing its report. See the console output.')
        counts = Counter(record['outcome'] for record in result['records'])
        result.update({key: counts[key] for key in ('passed', 'failed', 'skipped')})
        for record in result['records']:
            record['detail'] = record.get('detail','').replace(str(work), '<workspace>')
            if record['outcome'] != 'passed':
                record['tip'] = coaching_tip(record['nodeid'], record['detail'], lesson)
        expected = lesson.get('expected_tests')
        result['success'] = bool(process.returncode == 0 and result['collected'] > 0
                                 and result['passed'] == result['collected']
                                 and not result['failed'] and not result['skipped']
                                 and not result['collection_errors'] and not result['timed_out']
                                 and not result['output_limit']
                                 and (expected is None or expected == result['collected']))
        if result['timed_out']:
            result['tips'] = [f'The run exceeded {timeout_s:g} seconds and was stopped. Check infinite loops, blocking work or tasks that never finish.']
        elif result['output_limit']:
            result['tips'] = ['The run printed more than 256 KB and was stopped. Remove a noisy print loop before retrying.']
        elif result['success']:
            result['tips'] = ['All selected acceptance tests passed for this submission.', lesson['explanation'],
                              'Passing this suite does not prove correctness for every possible input. Try a new edge case and explain one trade-off.']
        elif result['collection_errors']:
            result['tips'] = ['The test suite could not finish collecting/running. Check imports, module-level code and signatures in the error output.']
        else:
            result['tips'] = ['Fix one failing behaviour at a time. Open a test below to see the real pytest assertion and a targeted coaching cue.']
        result['elapsed'] = round(time.monotonic()-started, 3)
        return result


def reference_text(lesson: dict) -> str:
    text = (ROOT/'references'/lesson['pack']/lesson['file']).read_text(encoding='utf-8')
    # Guided stages reveal only the current function, never future stages.
    if lesson['pack'] == 'guided':
        tree = ast.parse(text)
        return '\n\n'.join(ast.get_source_segment(text,n) or '' for n in tree.body
                           if isinstance(n,(ast.FunctionDef,ast.AsyncFunctionDef))
                           and n.name in lesson['targets'])
    return text


def discussion_feedback(lesson: dict, text: str) -> dict:
    if not isinstance(text, str) or len(text) > 30_000:
        raise ValueError('Use an answer under 30,000 characters.')
    words = re.findall(r"\b[\w’-]+\b", text)
    lowered = text.casefold()
    cues = []
    for label, options in lesson['cues']:
        matches = [term for term in options if term.casefold() in lowered]
        cues.append({'label': label, 'matches': matches, 'found': bool(matches)})
    # These are structure cues. They deliberately do NOT decide truth or quality.
    return {'submitted_text':text, 'word_count':len(words), 'estimated_seconds':round(len(words)/135*60),
            'cues':cues, 'has_number':bool(re.search(r'\d', text)),
            'has_first_person':bool(re.search(r'\b(I|my)\b', text, re.I)),
            'can_review':len(words)>=25,
            'note':'Keyword/length checks only, not semantic grading. A matched word does not prove a point is well explained or true. Review the visible rubric yourself.'}
